### ISSUE TITLE
[BUG] Temporal Beacon mirroring healing of multiple mages

### ISSUE THREAD

**Issue by CharWS** [CharWS/season-of-discovery-bugs#10]
#### 1.1. Description
When multiple mages have applied temporal beacon to separate players the damage of each mage heals each beacon (including ones that are not their own).
  #### 1.2. How to Reproduce
           1. get two mages and ensure that both have engraved temporal beacon
           3. have each mage apply their temporal beacon to a different target
           4. have one mage do some arcane damage
           5. note that each target receives healing

#### 2.1. Description
Similar effects such as beacon of light and atonement only heal players when the owner of the buff does healing or damage, not when other players do damage or healing too. It would follow that temporal beacons should only heal from damage done by the mage who has applied them.

**Comment by Twizzles** [comment]
Confirmed fixed.
