### ISSUE TITLE
[BUG] Able to Overpower while being disarmed and dual wielding

### ISSUE THREAD

**Issue by TheGroxEmpire** [CharWS/season-of-discovery-bugs#16]
#### 1.1. Description
While being disarmed and dual wielding, Overpower can still be cast as if the character still has a main hand equipped. 
  #### 1.2. How to Reproduce
           1. Be disarmed while dual wielding weapons
           2. Get a dodge while being disarmed
           3. Cast Overpower while being disarmed
  #### 1.3  Source Material
[Warcraft logs link](https://vanilla.warcraftlogs.com/reports/r9qaY4Q3NtPKdLxb#type=damage-done&boss=-3&difficulty=0&source=23&view=events&start=1188447&end=1198314)
![image](https://github.com/CharWS/season-of-discovery-bugs/assets/47816228/6bfe97bd-8dcc-4283-b4a0-417850edfb0c)
![image](https://github.com/CharWS/season-of-discovery-bugs/assets/47816228/fd10a008-ea10-45ac-94d3-6c472a148016)

#### 2.1. Description
Overpower requires a weapon to be cast. Like other similar weapon-based ability, it should not be able to be cast while being disarmed.
  #### 2.2 Source Material
N/A

**Comment by CharWS** [comment]
looks to be 1.12 accurate, the ability just checks for a melee weapon equipped so with an offhand still available can still use overpower despite the mh being disarmed
