### ISSUE TITLE
[BUG] Deep Wounds randomly stops proccing

### ISSUE THREAD

**Issue by TheGroxEmpire** [CharWS/season-of-discovery-bugs#17]
#### 1.1. Description

Currently there's an odd bug where Deep Wounds could suddenly stop proccing. This bug has been reported for at least three times. On two counts, the bug happened for the whole raid. Two different players reported that they had Deep Wounds talented and did not proc Deep Wounds inside BFD. The evidence for both reports are attached in 1.3.1 and 1.3.2. Both players claimed that they had Deep Wounds talented and that it worked before and after the raid, but not inside BFD. It's not obvious what's causing Deep Wounds to not proc here.

The third report however, has a log that shows the player losing the ability to have Deep Wounds in the middle of a raid combat. The player was disarmed by Murkshallow Snapclaw, and that disarm caused the player to lose Deep Wounds proc for the entire raid. The evidence are attached in 1.3.3.

  #### 1.2. How to Reproduce
          Currently there's no clear indication on how to reproduce it.

  #### 1.3  Source Material
<details>
  <summary><strong>1.3.1 Deep Wounds not proccing on entire raid (1)</strong></summary>

  Logs: https://vanilla.warcraftlogs.com/reports/gcbVfCpH1Y62yj4h#boss=-3&difficulty=0&type=damage-done&source=6

</details>

<details>
  <summary><strong>1.3.2 Deep Wounds not proccing on entire raid (2)</strong></summary>

  Logs: https://vanilla.warcraftlogs.com/reports/frPjYCHmnt7G1WTz#boss=-3&difficulty=0&type=damage-done&source=4

</details>

<details>
  <summary><strong>1.3.3 Deep Wounds not proccing after being disarmed</strong></summary>

The player (Googlethat) has Deep Wounds proccing until [2nd trash fight in the logs](https://vanilla.warcraftlogs.com/reports/6H7ZathF9mbQc2vr#type=auras&view=events&spells=debuffs&hostility=1&ability=412609&boss=-3&difficulty=0&target=64).

![image](https://github.com/CharWS/season-of-discovery-bugs/assets/47816228/0b41e08b-4b4f-480a-ab66-713625529e44)

Googlethat was disarmed by Murkshallow Snapclaw [after the last Deep Wound procs](https://vanilla.warcraftlogs.com/reports/6H7ZathF9mbQc2vr#type=summary&fight=4&view=events&source=64). No Deep Wounds proc from Googlethat right after that disarm.

![image](https://github.com/CharWS/season-of-discovery-bugs/assets/47816228/8ece641a-3290-4dcd-9006-ad83d7e70882)

</details>

#### 2.1. Description
Deep Wounds should not stop proccing mid raid.
  #### 2.2 Source Material
N/A

**Comment by Artemishowl** [comment]
Heya! 

This should be fixed, but if you see this happening again in this new patch, please update with more information.

**Comment by TheGroxEmpire** [comment]
Thank you, and will do! I'll mark this as fixed for now and close the issue.
