### ISSUE TITLE
[BUG] Living Flame does not get damage increase from Arcane Power or Arcane Instability 

### ISSUE THREAD

**Issue by chaoticmask** [CharWS/season-of-discovery-bugs#19]
#### 1.1. Description
Using Living Flame while under effect of Arcane Power should increase LF damage, same with having Arcane Instability talented
  #### 1.2. How to Reproduce
          1. Use Living Flame
          2. Note damage
          3. Use Arcane Power and Living Flame while having AP up
          4. Note damage again
  #### 1.3  Source Material
          1. https://vanilla.warcraftlogs.com/reports/DrYBW2AbMCp1f7Nx#fight=1&type=summary&pins=2%24Off%24%23244F4B%24expression%24source.name%20%3D%20'Yesmommy'&view=events LF with no AP (there is no AP buff event, while fight is longer than 15s - proofs AP was not used)
          2. https://vanilla.warcraftlogs.com/reports/DrYBW2AbMCp1f7Nx#fight=3&type=summary&pins=2%24Off%24%23244F4B%24expression%24source.name%20%3D%20'Yesmommy'&view=events Arcane Power into Living Flame cast deals same damage as in log above
          3. No log for Arcane instability since it's hard to show having/missing talent, but same behavior asArcane Power logs above
#### 2.1. Description
Both Arcane Power and Arcane Instability should increase damage of LF, as other sources of % damage work

**Comment by Twizzles** [comment]
Fixed as of this evening 2-13-24
