### ISSUE TITLE
[BUG] Mob fire ward making mobs immune to Living Flame

### ISSUE THREAD

**Issue by Twizzles** [CharWS/season-of-discovery-bugs#26]
#### 1.1. Description
Previously fire ward used by some mobs did not make them immune to Living Flame (fire and arcane damage). Since P2 patch <https://www.wowhead.com/classic/spell=4979/quick-flame-ward> this fire ward from specific mobs (Skeletal Warders and Ogres in Duskwood) is making them immune to Living flame damage. Other mobs such as Nekrosh in Wetlands are immune to fire but still take damage from living flame. 
  #### 1.2. How to Reproduce
          1. Go to duskwood. 
          2.  Engage Skeletal Warders or Orge Magi
          3. Cast Living Flame when fire Ward is up. 
  #### 1.3  Source Material
I don’t have a video at this time. 
#### 2.1. Description
Prior to P2 this was not the case. 
  #### 2.2 Source Material
None available

**Comment by Twizzles** [comment]
This is also supposedly occurring with frost wards making mobs immune to frostfire bolt and spellfrost bolt.

**Comment by CharWS** [comment]
This looks to be the intended interaction and matches the interaction for other versions of the spells such as in wotlk.

**Comment by Twizzles** [comment]
Weird. I wonder why it worked during P1. Glad they fixed it then
