### ISSUE TITLE
[BUG] Living Flame with multiple mages

### ISSUE THREAD

**Issue by CharWS** [CharWS/season-of-discovery-bugs#6]
#### 1.1. Description
When living flame is applied by multiple mages to the same target only the first applied will deal damage. 
  #### 1.2. How to Reproduce
           1. find another mage
           2. make sure you both have living flame rune engraved
           3. use living flame on an enemy
           4. have the other mage use living flame on that enemy
           5. note that only one does damage as long as both are applied

#### 2.1. Description
When multiple players apply personal dots to the same target it's expected that each dot will tick rather than overwriting each other.

**Comment by Twizzles** [comment]
Confirmed fixed
